server:
 port: 8762

#spring setting
spring:
  application:
    name: service-hi
#  zipkin:
#    base-url: http://localhost:9411

#eureka setting
eureka:
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/